name: news_portal
description: "뉴스 포탈 앱"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7+1
  google_fonts: ^6.2.1
  lucide_icons_flutter: ^3.0.2
  easy_extension:
    git:
      url: https://github.com/scadasystems/Easy-Extension.git
  go_router: ^15.1.1
  provider: ^6.1.5
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
